package tests;

import org.custommonkey.xmlunit.DetailedDiff;
import org.custommonkey.xmlunit.Diff;
import org.custommonkey.xmlunit.XMLUnit;
import org.xml.sax.SAXException;

import java.io.*;
import java.util.List;

public class CheckThatOrderGeneratedInAppEqualToOrderGeneratedInBackend {

//    Here should be a code to parse an order table from HTML (probably) and convert it to XML.
//    Then we need to access the generated by Backend system XML file and compare them. Getting XML file or response from the Backend could be done
//    via SOAPUI (most probably, because the XML is used, in other case it could be a JSON file, which we could get via some REST API.
//    But in this task we don't have any generated Order Table and the XML example is also not valid. The XML file has several typos/errors
//    (no start/ending tags e.g <customeName>custUserName</customerref>) so I could not use it also.
//     The example code could be something like one below


        public static void main(String args[]) throws FileNotFoundException,
                SAXException, IOException {

            // reading two xml file to compare in Java program
            FileInputStream fis1 = new FileInputStream("/Users/okalashnik/Downloads/testReport.xml");    //we can take from Backend
            FileInputStream fis2 = new FileInputStream("/Users/okalashnik/Downloads/testReport2.xml");    //we can take it from the app from the order Tables and convert to XML


            // using BufferedReader for improved performance
            BufferedReader source = new BufferedReader(new InputStreamReader(fis1));
            BufferedReader target = new BufferedReader(new InputStreamReader(fis2));

            //configuring XMLUnit to ignore white spaces
            XMLUnit.setIgnoreWhitespace(true);

            //comparing two XML using XMLUnit in Java
            List differences = compareXML(source, target);

            //showing differences found in two xml files
            printDifferences(differences);

        }

        public static List compareXML(Reader source, Reader target) throws
                SAXException, IOException {

            //creating Diff instance to compare two XML files
            Diff xmlDiff = new Diff(source, target);

            //for getting detailed differences between two xml files
            DetailedDiff detailXmlDiff = new DetailedDiff(xmlDiff);

            return detailXmlDiff.getAllDifferences();
        }

        public static void printDifferences(List differences) {
            int totalDifferences = differences.size();
            System.out.println("===============================");
            System.out.println("Total differences : " + totalDifferences);
            System.out.println("================================");

            for (Object difference : differences) {
                System.out.println(difference);
            }
        }
    }
